AWSTemplateFormatVersion: 2010-09-09
Description: LinkedIn Scraper that runs on AWS lambda serverless
    
Parameters:
    BucketName:
        Description: S3 Bucket
        Type: String    

    AudienceID:
        Description: LinkedIn Audience ID
        Type: Integer
        Default: 200

    SourceFolder:
        Description: folder in S3 Bucket where input files are located (lambda)
        Type: String
        Default: "src"

    Scrape:
        Description: Scrape an audience (True) or enrich it? (False)
        Type: Boolean
        Default: True

    ProxyNumID:
        Description: Proxy ID
        Type: Integer
        Default: 1


Resources:

    ScrapeFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - lambda.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Policies:
                -   PolicyName: Allow-logs
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 'logs:CreateLogGroup'
                            - 'logs:CreateLogStream'
                            - 'logs:PutLogEvents'
                            Resource: arn:aws:logs:*:*:*   
                -   PolicyName: BucketGetPutObject
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 's3:GetObject'
                            - 's3:PutObject'
                            Resource: 
                                Fn::Join: ["", ["arn:aws:s3:::", Ref: "BucketName", "/*"]] 
                

    ScrapeFunction:
        Type: AWS::Lambda::Function
        Properties:
            Runtime: python3.7
            Description: Function to scrape linkedin.
            Handler: src/lambda_function.lambda_handler
            Role: 
                Fn::GetAtt: [ "ScrapeFunctionRole", "Arn" ]
            Environment:
                Variables:
                    PYTHONPATH: "/var/task/src:/opt/python"
                    PATH: "/opt/bin:/opt/bin/lib"
                    BUCKET:
                        Ref: BucketName
                    AUDIENCE_ID:
                        Ref: AudienceID
                    SCRAPE:
                        Ref: Scrape
            Timeout: 900
            MemorySize: 4096
            Code:
                S3Bucket: 
                    Ref: BucketName
                S3Key: 
                    Fn::Sub: '${SourceFolder}/ScreenshotFunction.zip'
            Layers:
                - Ref: ScrapingSeleniumLayer

    ScrapingSeleniumLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            CompatibleRuntimes:
                - python3.11
                - python3.12
            Content:
                S3Bucket: 
                    Ref: BucketName
                S3Key: 
                    Fn::Sub: '${SourceFolder}/ScrapingSeleniumLayer.zip'
            Description: Scraping Linkedin Layer for Python3.6

