version: '3'

services:
  lambda:
    build: .
    environment:
      - PYTHONPATH=/var/task/src:/var/task/lib
      - PATH=/opt/bin
      - BUCKET=${BUCKET}
      - AUDIENCE_ID=${AUDIENCE_ID}
      - SCRAPE=${SCRAPE}
      - PROXYID=${PROXYID}
    volumes:
      - ./src/:/var/task/src/
      - ./tmp/:/tmp/
